# DockerFile

# ----- ----- ----- ----- -----
# Using Alpine base image
FROM alpine:latest

USER root

RUN apk update && \
	apk upgrade

RUN mkdir -p /data/plugins
COPY ./plugins/* /data/plugins/

COPY ./jdk*.tar.gz /java/
RUN tar -zxvf /java/jdk*.tar.gz -C /java/
RUN rm -r /java/*tar.gz

RUN mv /java/jdk* /java/current
ENV JAVA_HOME=/java/current
ENV PATH=$PATH:$JAVA_HOME/bin
RUN echo "#!/bin/sh" >> /etc/profile.d/java.sh && \
	echo "export JAVA_HOME=/java/current" >> /etc/profile.d/java.sh && \
	echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile.d/java.sh && \
	/bin/sh /etc/profile.d/java.sh

RUN apk add paxctl
RUN cd /java/current/bin && \
	paxctl -c java; paxctl -m java && \
	paxctl -c javac; paxctl -m javac

COPY ./*.jar /data/
RUN mv /data/*.jar /data/paper.jar
RUN echo eula=true > /data/eula.txt


EXPOSE 25565

CMD /java/current/bin/java -Xms4G -Xmx4G -jar /data/paper.jar --nogui
